# Generated by Django 3.1.5 on 2021-01-24 22:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_header_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to),
        ),
    ]
